// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("Bogus Fake Data Generator for .NET with FakeItEasy")]
[assembly: AssemblyProductAttribute("Bogus.FakeItEasy")]
[assembly: AssemblyCompanyAttribute("Brian Chavez")]
[assembly: AssemblyCopyrightAttribute("Brian Chavez © 2015")]
[assembly: AssemblyVersionAttribute("0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0-localbuild built on 1/1/2015 12:00:00 AM")]
[assembly: AssemblyTrademarkAttribute("Apache License v2.0")]
[assembly: AssemblyDescriptionAttribute("https://github.com/bchavez/Bogus")]
[assembly: InternalsVisibleToAttribute("Bogus.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Bogus Fake Data Generator for .NET with FakeItEasy";
        internal const System.String AssemblyProduct = "Bogus.FakeItEasy";
        internal const System.String AssemblyCompany = "Brian Chavez";
        internal const System.String AssemblyCopyright = "Brian Chavez © 2015";
        internal const System.String AssemblyVersion = "0.0.0";
        internal const System.String AssemblyFileVersion = "0.0.0";
        internal const System.String AssemblyInformationalVersion = "0.0.0-localbuild built on 1/1/2015 12:00:00 AM";
        internal const System.String AssemblyTrademark = "Apache License v2.0";
        internal const System.String AssemblyDescription = "https://github.com/bchavez/Bogus";
        internal const System.String InternalsVisibleTo = "Bogus.Tests";
    }
}
