// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Bogus Fake Data Generator for .NET")]
[assembly: AssemblyProductAttribute("Bogus")]
[assembly: AssemblyCompanyAttribute("Brian Chavez")]
[assembly: AssemblyCopyrightAttribute("Brian Chavez © 2016")]
[assembly: AssemblyVersionAttribute("0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0-localbuild built on 10/11/2016 5:10:40 PM")]
[assembly: AssemblyTrademarkAttribute("Apache License v2.0")]
[assembly: AssemblyDescriptionAttribute("http://www.github.com/bchavez/Bogus")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Bogus Fake Data Generator for .NET";
        internal const System.String AssemblyProduct = "Bogus";
        internal const System.String AssemblyCompany = "Brian Chavez";
        internal const System.String AssemblyCopyright = "Brian Chavez © 2016";
        internal const System.String AssemblyVersion = "0.0.0";
        internal const System.String AssemblyFileVersion = "0.0.0";
        internal const System.String AssemblyInformationalVersion = "0.0.0-localbuild built on 10/11/2016 5:10:40 PM";
        internal const System.String AssemblyTrademark = "Apache License v2.0";
        internal const System.String AssemblyDescription = "http://www.github.com/bchavez/Bogus";
    }
}
